[package]
name = "rendy-command"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"

[dependencies]
gfx-hal = "0.1"
derivative = "1.0"
failure = "0.1"
relevant = { version = "0.4", features = ["log", "backtrace"] }
smallvec = "0.6"
