[package]
name = "rendy-factory"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"

[features]
empty = ["gfx-backend-empty", "rendy-wsi/gfx-backend-empty"]
dx12 = ["gfx-backend-dx12", "rendy-wsi/gfx-backend-dx12"]
metal = ["gfx-backend-metal", "rendy-wsi/gfx-backend-metal"]
vulkan = ["gfx-backend-vulkan", "rendy-wsi/gfx-backend-vulkan"]
serde-1 = [
    "serde",
    "rendy-memory/serde-1",
    "gfx-hal/serde",
]

[dependencies]
rendy-memory = { version = "0.1", path = "../memory" }
rendy-resource = { version = "0.1", path = "../resource" }
rendy-command = { version = "0.1", path = "../command" }
rendy-wsi = { version = "0.1", path = "../wsi" }

gfx-hal = "0.1"
gfx-backend-empty = { version = "0.1.0", optional = true }
gfx-backend-dx12 = { version = "0.1.0", optional = true }
gfx-backend-metal = { version = "0.1.0", optional = true }
gfx-backend-vulkan = { version = "0.1.0", optional = true }

derivative = "1.0"
either = "1.0"
failure = "0.1"
log = "0.4"
parking_lot = "0.7"
relevant = { version = "0.4", features = ["log", "backtrace"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
smallvec = "0.6"
winit = "0.18"
