[package]
name = "rendy-texture"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
description = "Crate for rendy to create and use textures"
keywords = ["graphics", "rendy"]
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/rustgd/rendy.git"
documentation = "https://docs.rs/crate/rendy-texture/0.1.0"
edition = "2018"

[features]
serde-1 = ["serde", "gfx-hal/serde", "rendy-factory/serde"]

[dependencies]
rendy-command = { version = "0.1.0", path = "../command" }
rendy-memory = { version = "0.1.0", path = "../memory" }
rendy-resource = { version = "0.1.0", path = "../resource" }
rendy-factory = { version = "0.1.0", path = "../factory" }
rendy-util = { version = "0.1.0", path = "../util" }

gfx-hal = "0.1"

derivative = "1.0"
failure = "0.1"
serde = { version = "1.0", optional = true }
