[package]
name = "rendy-frame"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"

[dependencies]
derivative = "1.0"
either = "1.5"
gfx-hal = "0.1"
failure = "0.1"
log = "0.4"
relevant = { version = "0.4", features = ["log", "backtrace"] }
smallvec = "0.6"
rendy-command = { version = "0.1.0", path = "../command" }
rendy-factory = { version = "0.1.0", path = "../factory" }
rendy-memory = { version = "0.1.0", path = "../memory" }
rendy-resource = { version = "0.1.0", path = "../resource" }
